// generated by Fast Light User Interface Designer (fluid) version 1.0104

#include "window.h"

Fl_Double_Window* UserInterface::make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(109, 100);
    w = o;
    o->user_data((void*)(this));
    new Fl_Button(25, 25, 25, 25);
    o->end();
  }
  return w;
}
