/*********************************************************
 *  Filename: glcd.c
 *  Generated by Python script glcd.py
 *   using Python Imaging Library (PIL)
 *   2010-04-16 11:13:25.986308
 *  Input picture: glcd.bmp
 *  Image Format: BMP
 *  Image Size: (240, 128L)
 *  Image Mode: RGB
 *********************************************************/

data = "";

/*********************************************************/
