#!/usr/bin/env/python
# -*- coding: utf8 -*-

from writer import Writer

class Writer_ASM(Writer):
	
	def header(self):
		self.fd.write("""\t\t;  \tGraphic controller: %(gcontroller)s
\t\t;  \tFilename: %(output)s
\t\t;  \tGenerated by Python script glcd.py
\t\t;  \t using Python Imaging Library (PIL)
\t\t;  \t  http://www.pythonware.com/products/pil/
\t\t;  \t %(now)s
\t\t;  \tInput picture: %(input)s
\t\t;  \tImage Format: %(format)s
\t\t;  \tImage Size: %(size)s
\t\t;  \tImage Mode: %(mode)s

""" % self.params)

	def append(self, d):
	
		if self.sp==1:
			self.fd.write("\tDA\t")
		
		self.fd.write("0x%02X" % d)
		
		self.i = self.i + 1
		
		self.space_data(" , ")

	def footer(self):
		self.fd.write("""\t; \t\tEOF
""" % self.params)