all:
	# Faire un lien sybolique : ln -s /usr/lib/jdk-1.4.2_04/bin/ /usr/bin/
	javac *.java
	#gcj --classpath=/usr/include/javax/,/usr/include/java -C *.java

run:
	appletviewer index.html
	#firefox index.html
	#mozilla-firefox index.html
	#mozilla index.html