// generated by Fast Light User Interface Designer (fluid) version 1.0104

#include "window.h"

Fl_Output *txtOutput=(Fl_Output *)0;

Fl_Button *butOK=(Fl_Button *)0;

static void cb_butOK(Fl_Button* o, void*) {
  //butOK->butOK_Pressed(((Fl_Button *)o)->value());
}

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(310, 105);
    w = o;
    txtOutput = new Fl_Output(25, 25, 255, 25);
    { Fl_Button* o = butOK = new Fl_Button(25, 50, 255, 30, "&Ok");
      o->callback((Fl_Callback*)cb_butOK);
    }
    o->end();
    o->resizable(o);
  }
  return w;
}
