// generated by Fast Light User Interface Designer (fluid) version 1.0104

#ifndef window_h
#define window_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Output.H>
extern Fl_Output *txtOutput;
#include <FL/Fl_Button.H>
extern Fl_Button *butOK;
Fl_Double_Window* make_window();
#endif
