#CC=gcc # Linux x86
#CC=arm-wince-pe-gcc # Windows CE on ARM processor(iPaq) (pocketpc-gcc)
#CC=arm-linux-gcc # Linux Handhelds Familiar on ARM processor (iPaq) classic toolchain
CC=/scratchbox/compilers/arm-linux-ct401-2.3/bin/arm-unknown-linux-gnu-gcc-4.0 # Linux Handhelds Familiar on ARM processor using Scratchbox


all:
	$(CC) main.c