######################################################################
# Automatically generated by qmake (2.01a) mer. juin 20 16:55:40 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . /usr/local/qwt-5.0.2/include /usr/include/qwt 
#/usr/include/qt3
#LIBS += -Lpath/to/qwt/lib -lqwt
LIBS += -L/usr/local/qwt-5.0.2/lib -lqwt

# Input
SOURCES += main.cpp
