######################################################################
# Automatically generated by qmake (2.01a) ven. juin 22 16:15:52 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qprogressbar_gradient.h
SOURCES += main.cpp qprogressbar_gradient.cpp
