PYTHON = python

all:
	$(MAKE) crypt

crypt13:
	$(PYTHON) rot13.py < file.txt
	
decrypt13:
	$(PYTHON) rot13.py < file_encrypted.txt

cryptall:
	$(PYTHON) rot.py < file.txt
	
decryptall:
	$(PYTHON) rot.py < file_encrypted.txt
