######################################################################
# Automatically generated by qmake (2.01a) mer. juil. 4 11:31:16 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ticker.h
SOURCES += main.cpp ticker.cpp
